import { useEffect } from "react";
import { AlertTriangle } from "lucide-react";

export default function TermsPage() {
  useEffect(() => {
    document.title = "Terms of Service | Afrixplorer";
  }, []);

  return (
    <div className="max-w-2xl space-y-8">
      <div className="space-y-2">
        <h1 className="text-xl font-semibold tracking-tight">Terms of Service</h1>
        <p className="text-sm text-muted-foreground">Last updated: September 8, 2026</p>
      </div>

      <div className="flex items-start gap-3 rounded-lg border border-amber-500/30 bg-amber-500/10 px-4 py-3">
        <AlertTriangle size={16} className="mt-0.5 shrink-0 text-amber-600 dark:text-amber-400" />
        <p className="text-xs leading-relaxed text-amber-800 dark:text-amber-300">
          This document is a general-purpose template and has not been reviewed by a lawyer. It has not been
          finalized for a specific governing jurisdiction (see Section 9). Do not rely on it as a complete legal
          agreement without independent legal review appropriate to where you operate and where your users are
          located.
        </p>
      </div>

      <section className="space-y-2">
        <h2 className="text-sm font-semibold">1. Acceptance of Terms</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          By accessing or using Afrixplorer ("the Service"), operated by Blaise Sebagabo ("we", "us", "our"), you
          agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-sm font-semibold">2. Description of Service</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Afrixplorer provides access to agricultural production, yield, trade, and economic data for African
          countries, aggregated from public sources including FAOSTAT, World Bank Open Data, UN Comtrade, and WFP.
          The Service is provided for informational and research purposes only.
        </p>
        <p className="text-sm leading-relaxed text-muted-foreground">
          <strong className="text-foreground">Afrixplorer is not a source of financial, investment, or legal
          advice.</strong> "Investment signal" scores, insights, and any commentary generated by the Service are
          computed programmatically from historical data and are not recommendations to buy, sell, or invest in
          anything. Always conduct independent due diligence and consult a qualified professional before making
          investment decisions.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-sm font-semibold">3. Accounts</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Some features require creating an account. You agree to provide accurate information and to keep your
          login credentials confidential. You are responsible for all activity under your account. Notify us
          immediately at hello@afrixplorer.io if you suspect unauthorized access.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-sm font-semibold">4. Acceptable Use</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">You agree not to:</p>
        <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
          <li>Scrape, systematically extract, or bulk-download data beyond what CSV export features explicitly permit</li>
          <li>Resell or redistribute the Service's data or derived products as a competing data product without permission</li>
          <li>Attempt to circumvent rate limits, authentication, or access controls</li>
          <li>Use the Service to violate any applicable law</li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-sm font-semibold">5. Data & Intellectual Property</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          The underlying source data (FAOSTAT, World Bank, UN Comtrade, WFP) is publicly available data and remains
          subject to each source's own license and terms — see each source's website for details. The Service's
          aggregation, computed metrics, visualizations, design, and software are the property of Blaise Sebagabo and
          may not be copied or reproduced without permission, except where a specific feature (e.g. CSV export)
          explicitly permits it.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-sm font-semibold">6. Paid Plans</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Paid subscription billing is not yet active on the Service. Where paid plans are introduced, updated terms
          covering billing, renewal, and cancellation will be posted here and, where required by law, presented for
          separate acceptance before purchase.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-sm font-semibold">7. Disclaimer & Limitation of Liability</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          The Service is provided "as is" without warranties of any kind. While we make reasonable efforts to ensure
          data accuracy, the complexity of aggregating and normalizing large government and multilateral datasets
          means errors, gaps, or delays are possible. We are not liable for any loss or damage arising from reliance
          on data or insights provided by the Service, to the maximum extent permitted by applicable law.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-sm font-semibold">8. Changes to These Terms</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          We may update these Terms from time to time. Material changes will be reflected by updating the "Last
          updated" date above. Continued use of the Service after changes constitutes acceptance of the revised
          Terms.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-sm font-semibold">9. Governing Law</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          [JURISDICTION — to be specified]. These Terms should be interpreted under the laws of the jurisdiction
          where the operator is legally established, without regard to conflict-of-law principles. This section is a
          placeholder and should be completed based on where the Service is actually operated from.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-sm font-semibold">10. Contact</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Questions about these Terms: <a href="mailto:hello@afrixplorer.io" className="text-primary hover:underline">hello@afrixplorer.io</a>
        </p>
      </section>
    </div>
  );
}
