// Data layer that loads from agriscope.db (SQLite, generated by refresh-data.py)
// Falls back to embedded baseline data if the live file is missing

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import Database from "better-sqlite3";

// ──────────────────── Types ────────────────────

type CropTimeSeries = Record<string, number>;
type CropElements = { production: CropTimeSeries; yield: CropTimeSeries; area: CropTimeSeries };
type CountryCrops = Record<string, CropElements>;

export interface DataMetadata {
  lastUpdated: string;
  sources: Record<string, { name: string; url: string; description: string; status: string }>;
  countries: { name: string; code: string; region: string }[];
  crops: string[];
  years: string[];
  errors: string[];
}

export interface BestPrice {
  price: number;
  year: string;
  source: string;       // e.g. "FAOSTAT 2024" or "West Africa avg"
  isEstimate: boolean;
  isProcessedProxy: boolean;  // true when e.g. Maize flour → Maize grain
}

// ──────────────────── SQLite Connection ────────────────────

const __filename_esm = typeof __filename !== 'undefined' ? __filename : fileURLToPath(import.meta.url);
const __dirname_esm = typeof __dirname !== 'undefined' ? __dirname : path.dirname(__filename_esm);
const DB_PATH = path.join(__dirname_esm, "data", "agriscope.db");

let dbInstance: Database.Database | null = null;
let dbVerified = false;

function getDb(): Database.Database | null {
  if (dbVerified && dbInstance) return dbInstance;
  
  if (!fs.existsSync(DB_PATH)) {
    console.warn("[data] agriscope.db not found at", DB_PATH);
    return null;
  }
  
  try {
    const conn = new Database(DB_PATH, { readonly: true });
    conn.prepare("SELECT 1 FROM metadata LIMIT 1").get();
    dbInstance = conn;
    dbVerified = true;
    return dbInstance;
  } catch (e) {
    console.warn("[data] Failed to open agriscope.db:", e);
    return null;
  }
}

function getMetadataValue<T>(key: string, parseJson = true): T | null {
  const c = getDb();
  if (!c) return null;
  const row = c.prepare("SELECT value FROM metadata WHERE key = ?").get(key) as { value: string } | undefined;
  if (!row) return null;
  return (parseJson ? JSON.parse(row.value) : row.value) as T;
}

// ──────────────────── Exported Data ────────────────────

export function getMetadata(): DataMetadata {
  const dbConfig = getDb();
  if (!dbConfig) {
    return {
      lastUpdated: "2022-12-31T00:00:00Z",
      sources: {},
      countries: COUNTRIES_FALLBACK.map(c => ({ name: c.name, code: c.code, region: c.region })),
      crops: [...CROPS_FALLBACK],
      years: [...YEARS_FALLBACK],
      errors: ["Live data not available, using embedded baseline"],
    };
  }
  
  return {
    lastUpdated: getMetadataValue<string>("lastUpdated", false) || "",
    sources: getMetadataValue("sources") || {},
    countries: getMetadataValue("countries") || [],
    crops: getMetadataValue("crops") || [],
    years: getMetadataValue("years") || [],
    errors: getMetadataValue("errors") || [],
  };
}

export function getCountries() {
  return getMetadataValue<any[]>("countries") || COUNTRIES_FALLBACK;
}

export function getCrops(): string[] {
  return getMetadataValue<string[]>("crops") || [...CROPS_FALLBACK];
}

export function getYears(): string[] {
  return getMetadataValue<string[]>("years") || [...YEARS_FALLBACK];
}

export function getCropData(): Record<string, CountryCrops> {
  const c = getDb();
  if (!c) return CROP_DATA_FALLBACK;
  
  const rows = c.prepare("SELECT country, crop, element, year, value FROM crop_metrics").all() as any[];
  const res: Record<string, CountryCrops> = {};
  
  for (const row of rows) {
    if (!res[row.country]) res[row.country] = {};
    if (!res[row.country][row.crop]) {
      res[row.country][row.crop] = { production: {}, yield: {}, area: {} };
    }
    const elementsTarget = res[row.country][row.crop] as any;
    if (!elementsTarget[row.element]) elementsTarget[row.element] = {};
    elementsTarget[row.element][String(row.year)] = row.value;
  }
  return res;
}

export function getGlobalAvgYields(): Record<string, number> {
  const c = getDb();
  if (!c) return GLOBAL_AVG_YIELDS_FALLBACK;
  
  const rows = c.prepare("SELECT crop, yield_hg_ha FROM global_avg_yields").all() as any[];
  const res: Record<string, number> = {};
  for (const r of rows) {
    res[r.crop] = r.yield_hg_ha;
  }
  return res;
}

export function getWorldBankData(): Record<string, Record<string, Record<string, number | null>>> {
  const c = getDb();
  if (!c) return WORLD_BANK_FALLBACK;
  const rows = c.prepare("SELECT country, indicator, year, value FROM world_bank_metrics").all() as any[];
  
  const res: Record<string, Record<string, Record<string, number | null>>> = {};
  for (const row of rows) {
    if (!res[row.country]) res[row.country] = {};
    if (!res[row.country][row.indicator]) res[row.country][row.indicator] = {};
    res[row.country][row.indicator][String(row.year)] = row.value;
  }
  return res;
}

export function getTradeData(): Record<string, Record<string, Record<string, number>>> {
  const c = getDb();
  if (!c) return TRADE_DATA_FALLBACK;
  const rows = c.prepare("SELECT country, crop, year, value_usd_millions FROM trade_metrics WHERE element = 'export'").all() as any[];
  
  const res: Record<string, Record<string, Record<string, number>>> = {};
  for (const row of rows) {
    if (!res[row.country]) res[row.country] = {};
    if (!res[row.country][row.crop]) res[row.country][row.crop] = {};
    res[row.country][row.crop][String(row.year)] = row.value_usd_millions;
  }
  return res;
}

export function getImportData(): Record<string, Record<string, Record<string, number>>> {
  const c = getDb();
  if (!c) return {};
  const rows = c.prepare("SELECT country, crop, year, value_usd_millions FROM trade_metrics WHERE element = 'import'").all() as any[];
  
  const res: Record<string, Record<string, Record<string, number>>> = {};
  for (const row of rows) {
    if (!res[row.country]) res[row.country] = {};
    if (!res[row.country][row.crop]) res[row.country][row.crop] = {};
    res[row.country][row.crop][String(row.year)] = row.value_usd_millions;
  }
  return res;
}

export function getProducerPrices(): Record<string, Record<string, Record<string, number>>> {
  const c = getDb();
  if (!c) return {};
  const rows = c.prepare("SELECT country, crop, year, price_usd_tonne FROM price_metrics WHERE source = 'faostat'").all() as any[];
  const res: Record<string, Record<string, Record<string, number>>> = {};
  for (const row of rows) {
    if (!res[row.country]) res[row.country] = {};
    if (!res[row.country][row.crop]) res[row.country][row.crop] = {};
    res[row.country][row.crop][String(row.year)] = row.price_usd_tonne;
  }
  return res;
}

export function getWfpPrices(): Record<string, Record<string, Record<string, number>>> {
  const c = getDb();
  if (!c) return {};
  const rows = c.prepare("SELECT country, crop, year, price_usd_tonne FROM price_metrics WHERE source = 'wfp'").all() as any[];
  const res: Record<string, Record<string, Record<string, number>>> = {};
  for (const row of rows) {
    if (!res[row.country]) res[row.country] = {};
    if (!res[row.country][row.crop]) res[row.country][row.crop] = {};
    res[row.country][row.crop][String(row.year)] = row.price_usd_tonne;
  }
  return res;
}

export function getWfpProxyFlags(): Record<string, Record<string, boolean>> {
  const c = getDb();
  if (!c) return {};
  const rows = c.prepare("SELECT country, crop FROM price_metrics WHERE source = 'wfp' AND is_proxy = 1 GROUP BY country, crop").all() as any[];
  const res: Record<string, Record<string, boolean>> = {};
  for (const row of rows) {
    if (!res[row.country]) res[row.country] = {};
    res[row.country][row.crop] = true;
  }
  return res;
}

/**
 * Get the best available price for a country/crop.
 * Uses actual FAOSTAT data when recent (< 5yr old).
 * Falls back to regional average from peer countries with recent data.
 */
export function getBestPrice(country: string, crop: string): BestPrice | null {
  const c = getDb();
  if (!c) return null; // Using live db for best price calculation
  
  const currentYear = new Date().getFullYear();
  const staleThreshold = currentYear - 5;

  // 1. Try actual FAOSTAT prices for this country/crop first
  const faostatRows = c.prepare("SELECT year, price_usd_tonne FROM price_metrics WHERE country = ? AND crop = ? AND source = 'faostat' AND price_usd_tonne > 0 ORDER BY year DESC").all(country, crop) as any[];
  
  if (faostatRows.length > 0) {
    const latestYear = parseInt(faostatRows[0].year);
    if (latestYear >= staleThreshold) {
      // Recent data exists. Take average of up to 3 most recent years
      const recentRows = faostatRows.slice(0, 3);
      const avgPrice = recentRows.reduce((sum, r) => sum + r.price_usd_tonne, 0) / recentRows.length;

      // Outlier check against other countries' latest recent FAOSTAT price
      const allCountriesLatest = c.prepare(`
        SELECT pm.country, pm.price_usd_tonne
        FROM price_metrics pm
        JOIN (
          SELECT country, MAX(year) as max_year
          FROM price_metrics
          WHERE crop = ? AND source = 'faostat' AND price_usd_tonne > 0
          GROUP BY country
        ) latest ON pm.country = latest.country AND pm.year = latest.max_year
        WHERE pm.crop = ? AND pm.source = 'faostat' AND pm.year >= ?
      `).all(crop, crop, staleThreshold) as any[];

      const allRecentPrices = allCountriesLatest.map(r => r.price_usd_tonne).sort((a, b) => a - b);
      let isOutlier = false;
      if (allRecentPrices.length >= 3) {
        const median = allRecentPrices[Math.floor(allRecentPrices.length / 2)];
        isOutlier = avgPrice > median * 5;
      }

      if (!isOutlier) {
        return {
          price: Math.round(avgPrice),
          year: String(latestYear),
          source: `FAOSTAT ${latestYear}`,
          isEstimate: false,
          isProcessedProxy: false,
        };
      }
    }
  }

  // 2. Try WFP prices
  const wfpRows = c.prepare("SELECT year, price_usd_tonne, is_proxy FROM price_metrics WHERE country = ? AND crop = ? AND source = 'wfp' AND price_usd_tonne > 0 ORDER BY year DESC").all(country, crop) as any[];
  
  if (wfpRows.length > 0) {
    const latestYear = parseInt(wfpRows[0].year);
    if (latestYear >= staleThreshold) {
      const recentRows = wfpRows.slice(0, 3);
      const avgPrice = recentRows.reduce((sum, r) => sum + r.price_usd_tonne, 0) / recentRows.length;
      const isProxy = recentRows[0].is_proxy === 1;
      
      const proxyLabel = isProxy ? ", flour proxy" : "";
      return {
        price: Math.round(avgPrice),
        year: String(latestYear),
        source: `WFP ${latestYear} (est. farmgate${proxyLabel})`,
        isEstimate: true,
        isProcessedProxy: isProxy,
      };
    }
  }

  // 3. Use precomputed regional/continental estimate from Python script
  const estimateRow = c.prepare("SELECT year, price_usd_tonne, source FROM price_metrics WHERE country = ? AND crop = ? AND source LIKE '%avg' ORDER BY year DESC LIMIT 1").get(country, crop) as any;
  if (estimateRow) {
    return {
      price: Math.round(estimateRow.price_usd_tonne),
      year: String(estimateRow.year),
      source: estimateRow.source,
      isEstimate: true,
      isProcessedProxy: false,
    };
  }
  
  // 4. Fallback to stale FAOSTAT data
  if (faostatRows.length > 0) {
    const recentRows = faostatRows.slice(0, 3);
    const avgPrice = recentRows.reduce((sum, r) => sum + r.price_usd_tonne, 0) / recentRows.length;
    return {
      price: Math.round(avgPrice),
      year: String(faostatRows[0].year),
      source: `FAOSTAT ${faostatRows[0].year}`,
      isEstimate: false,
      isProcessedProxy: false,
    };
  }

  return null;
}

// ──────────────────── Fallback Constants ────────────────────

const COUNTRIES_FALLBACK = [
  { name: "Uganda", code: "UGA", region: "East Africa" },
  { name: "Kenya", code: "KEN", region: "East Africa" },
  { name: "Rwanda", code: "RWA", region: "East Africa" },
  { name: "Nigeria", code: "NGA", region: "West Africa" },
  { name: "Ghana", code: "GHA", region: "West Africa" },
  { name: "Tanzania", code: "TZA", region: "East Africa" },
];

const CROPS_FALLBACK = ["Maize", "Coffee", "Rice", "Cassava", "Cocoa", "Beans"];

const YEARS_FALLBACK = ["2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022"];

const GLOBAL_AVG_YIELDS_FALLBACK: Record<string, number> = {
  "Maize": 5900, "Coffee": 1100, "Rice": 4700, "Cassava": 11500, "Cocoa": 480, "Beans": 800,
};

const CROP_DATA_FALLBACK: Record<string, CountryCrops> = {};
const WORLD_BANK_FALLBACK: Record<string, Record<string, Record<string, number | null>>> = {};
const TRADE_DATA_FALLBACK: Record<string, Record<string, Record<string, number>>> = {};
